src/layout/SideBar/SideBar.style.ts
=> [fix] SVG 수정

src/components/Modal/AddCategory.tsx, src/layout/SideBar/SideBar.tsx, src/pages/Memo/page.tsx, src/stores/modules/category.ts, src/stores/modules/memo.ts
feat/#25-add-category -> dev
카테고리 추가 기능 구현
카테고리 추가 시 해당 카테고리 이동
텍스트 입력 시 현재 카테고리에 맞게 자동으로 카테고리 설정
=> #25 카테고리 추가 기능 구현

src/components/Memo/Text/MemoText.tsx, src/pages/Login/page.tsx, src/styles/theme.ts
feat/#30-design-system-> dev
디자인 시스템(폰트, 색상, radius, shadow) 추가 및 적용 테스트
=> #30 디자인 시스템 적용

src/components/SideBar/SideMessage/SideMessage.tsx, src/layout/SideBar/SideBar.tsx
=> #11 [feat] 전체메모 버튼 기능 추가

src/components/SideBar/SideMessage/SideMessage.Style.ts, src/components/SideBar/SideMessage/SideMessage.tsx
=> #11 [feat] 우클릭이벤트 생성

src/components/Modal/EditCategory.tsx, src/components/SideBar/SideMessage/SideMessage.tsx, src/stores/modules/category.ts
=> #11 [feat] 카테고리 변경 구현

src/components/SideBar/SideMessage/SideMessage.tsx, src/stores/modules/category.ts
=> #11 [feat] 카테고리 삭제 기능 구현

src/components/SideBar/SideMessage/SideMessage.tsx
=> #11 [feat] 모바일 우클릭 롱프레스로 대체

src/components/SideBar/SideMessage/SideMessage.Style.ts
=> #11 [fix] 모바일 롱클릭 기본 이벤트 블락

src/components/SideBar/SideMessage/SideMessage.tsx
=> #11 [feat] 드래그 스타일 적용

src/components/Modal/AddCategory.tsx, src/components/Modal/EditCategory.tsx, src/components/Modal/Modal.Style.ts
=> #11 [feat] 카테고리 추가/설정 모달 반응형 구현

src/components/Modal/Modal.Style.ts
=> #11 [feat] 모달 zIndex 수정

src/components/Modal/GatherContents.tsx
=> #44 [fix] 사이드바메뉴 겹치는 이슈  fix

src/components/SideBar/SideMessage/SideMessage.Style.ts, src/components/SideBar/SideMessage/SideMessage.tsx, src/components/SideBar/SideMessage/controllers/api.ts, src/components/SideBar/SideMessage/controllers/mock/category.ts, src/components/SideBar/SideMessage/controllers/mock/memo.ts, src/layout/SideBar/SideBar.style.ts
=> #11 [feat] 핀아이콘 수정

src/components/Modal/Modal.Style.ts, src/components/Modal/SearchCategory.tsx, src/layout/Header/Header.tsx, src/layout/MainLayout/MainLayout.tsx
=> #29 [feat] 검색 컴포넌트 UI 구현

src/components/Modal/SearchCategory.tsx
feat/#29 -> dev
각각 메모에 대한 카테고리명 표시되도록 수정함
=> #29 [feat] 검색 컴포넌트 카테고리 로직 변경

src/components/Modal/Search/Search.tsx, src/layout/Header/Header.tsx
feat/#29 -> dev
검색 결과 후 메모 클릭시 해당 케테고리로 이동
- 추후 해당 메모로 이동하도록 구현할지 PM과 상의해야 할듯
=> #29 [feat] 검색 결과 클릭시 해당 카테고리로 이동

.env, src/controllers/api.ts, src/controllers/mock/category.ts, src/pages/Memo/page.tsx, src/stores/modules/memo.ts, vite.config.ts
일단 카테고리 id 직접 목데이터 값 가져다가 써서 지정했습니다.
추후 카테고리 GET 있으면 그거 가지고 수정함
=> #54 [feat] 메인 컴포넌트 API 연결 임시 구현

src/controllers/api.ts, src/layout/SideBar/SideBar.tsx, src/pages/Memo/page.tsx
=> #9 [feat] 카테고리별 메모 표시

src/components/Modal/Search/Search.tsx, src/controllers/api.ts, src/pages/Memo/page.tsx
feat/#9 -> dev
이미지 메모 POST API 연결
- 근데 제대로 읽어오는지는 아직 확인못했음
=> #9 [feat] 이미지 메모 POST API 연결

src/components/SideBar/SideMessage/SideMessage.tsx
=> # 11 [feat] 모바일 롱클릭 이벤트 수정

src/components/SideBar/SideMessage/SideMessage.tsx, src/layout/MainLayout/MainLayout.tsx
=> #11 [feat] contextMenu 전역 컴포넌트 설정

src/components/SideBar/SideMessage/SideMessage.tsx
- [x] 기능 추가
feat/#9 -> dev
햄들다
- [x] 정상 작동!
=> #9 [feat] 누락된 드래그이벤트추가

src/hooks/useContextMenu.tsx
feat/#9 -> dev
하단에서 안짤리게 위치 조정
=> #9 [feat] 컨텍스트메뉴 위치 조정

src/components/SideBar/SideMessage/SideMessage.tsx, src/hooks/useContextMenu.tsx
=> #9 [feat] useContextMenu 수정

.env, .env.production, index.html, src/controllers/api.ts, src/pages/Login/page.tsx, src/pages/Oauth/KakaoCallback.tsx
=> [fix] 카카오로그인 헤더 수정

src/components/Modal/AddCategory.tsx, src/layout/Header/Header.tsx, src/layout/SideBar/SideBar.tsx, src/router/Root.tsx, src/stores/modules/category.ts, src/stores/modules/customBaseQuery.ts
=> [feat] 테스트용 커밋

src/pages/Memo/page.tsx, src/stores/config/configStore.ts, src/stores/modules/memo.ts
=> [feat] 테스트 커밋

src/components/Modal/Search/Search.tsx, src/stores/modules/memo.ts
=> #54 [Feat] 메모 API 테스트

.env, .env.production, src/components/Popup/Auth/Info/Info.tsx, src/components/Popup/Auth/Term/Term.tsx, src/pages/Login/page.tsx, src/pages/Oauth/KakaoCallback.tsx, src/pages/Root/page.tsx, src/router/Root.tsx, src/router/index.tsx
=> #54 [Feat] 로컬 서버 연결

src/pages/Memo/page.tsx, src/stores/modules/memo.ts
=> #54 [Fix] 메모 조회 로직 수정

src/components/Modal/Search/Search.tsx
=> #54 [Feat] 검색 API 연결

src/components/SideBar/SideMessage/SideMessage.tsx, src/layout/Header/Header.tsx, src/layout/MainLayout/MainLayout.tsx, src/layout/SideBar/SideBar.tsx
=> #11 [Feat] 사이드바 모바일  반응형 구현

src/pages/Memo/page.tsx, src/stores/modules/category.ts
=> #54 [Feat] 메모 수정

src/controllers/api.Type.ts, src/layout/Header/Header.tsx, src/layout/SideBar/SideBar.style.ts, src/layout/SideBar/SideBar.tsx, src/utils/Auth.ts
feat/#114-logout-button -> dev
로그아웃 버튼 구현
일단 임시로 사이드바에 집어넣음
추후에 설정 페이지 구현하면 거기에 넣을 예정
=> #114 [feat] 임시 로그아웃 버튼 구현

.env, .env.production, src/components/Popup/Auth/Info/Info.tsx, src/controllers/api.ts, src/pages/Login/page.tsx, src/pages/Oauth/Callback.tsx, src/router/index.tsx
=> #69 [Feat] 구글 로그인 추가

src/components/Modal/MemoDetail/Schedule/MemoDetailSchedule.tsx, src/components/Modal/MemoEditor/Schedule/MemoEditorSchedule.tsx, src/controllers/api.ts, src/controllers/mock/memo.ts, src/stores/modules/memo.ts
feat/#54-> dev
일정 추가 시, 장소, 알림 설정, 설명 input 추가
=> #54 [Feat] 일정 추가 로직 수정

src/components/Memo/Schedule/MemoSchedule.tsx, src/components/Modal/MemoEditor/Schedule/MemoEditorSchedule.tsx, src/stores/modules/memo.ts
- 일괄조회에 title, place, description, alarm 추가
- 변수명 수정
=> #54 [Feat] 일정 관련 수정 사항 반영

src/components/Memo/Memo.tsx, src/components/Modal/EditMemoCategory/EditMemoCategory.tsx
=> #54 [Feat] 메모 카테고리 변경 기능 구현 중

.env, src/components/Memo/Image/MemoImage.tsx, src/components/Memo/Memo.tsx, src/components/Modal/MemoCollection/Image/MemoCollectionImage.tsx, src/components/Modal/MemoCollection/Link/MemoCollectionLink.tsx, src/components/Modal/MemoDetail/Image/MemoDetailImage.Style.ts, src/components/Modal/MemoDetail/Image/MemoDetailImage.tsx, src/pages/Login/page.tsx, src/stores/modules/memo.ts, src/ts/Memo.Prop.ts
feat/#54-> dev
사잔/일정 조회 API 연동
사진 설명 추가
=> #54 [Feat] API 수정사항 연동

.env, src/components/Memo/Memo.tsx, src/components/Memo/Schedule/MemoSchedule.tsx, src/components/Modal/MemoCollection/MemoCollection.tsx, src/components/Modal/MemoDetail/Schedule/MemoDetailSchedule.tsx, src/components/Modal/MemoEditor/Schedule/MemoEditorSchedule.tsx, src/components/Popup/Auth/Term/Term.Style.ts, src/components/Popup/Auth/Term/Term.tsx, src/stores/modules/memo.ts
=> #54 [Feat] 일정 수정 API 추가

src/components/Modal/MemoCollection/Link/MemoCollectionLink.tsx, src/stores/modules/memo.ts
=> #134 [refactor] 링크컬렉션에서 카테고리 선택하면 썸네일에 카테고리명 미표시

src/components/Common/EmptyContent.ts, src/components/Modal/MemoCollection/Image/MemoCollectionImage.tsx, src/components/Modal/MemoCollection/Link/MemoCollectionLink.tsx, src/components/Modal/MemoCollection/Schedule/MemoCollectionSchedule.tsx
=> #140 [feat] 모아보기 컨텐츠 없을때 화면 추가

.gitignore, src/App.tsx, src/components/Memo/Image/MemoImage.tsx, src/components/Memo/Link/MemoLink.tsx, src/components/Modal/EditMemoCategory/EditMemoCategory.Style.ts, src/components/Modal/EditMemoCategory/EditMemoCategory.tsx, src/components/Modal/MemoCollection/Link/MemoCollectionLink.tsx, src/hooks/useChatLoader.ts, src/hooks/useOgData.ts, src/hooks/useStableImage.ts, src/pages/Login/page.tsx, src/pages/Memo/page.tsx, src/stores/modules/memo.ts
=> #150 [fix] api 수정

src/controllers/api.ts, src/pages/Login/page.tsx, src/router/index.tsx
=> #150 [fix] 카카오 API 수정

src/controllers/api.ts, src/pages/Login/LoginPage.style.ts, src/pages/Login/page.tsx, src/pages/Register/page.tsx, src/pages/Setting/page.tsx, src/stores/modules/memo.ts
=> #150 [feat] 네이버 로그인 추가
